//adds the name and image for each building button
export const buildings = [
  {
    name: "student center",
    heading: "Student Center Rooms",
    img: "/static/student center.jpeg",
    rooms: ["AB Conference Room", "Ballroom", "Alumni Lounge", "State Room"],
  },
  {
    name: "rahall",
    heading: "Rahall Building Rooms",
    img: "/static/rehall.jpeg",
    rooms: ["103", "119", "128", "303", "304", "311", "315", "318"],
  },
  {
    name: "university point",
    heading: "University Point Rooms",
    img: "/static/university point.jpeg",
    rooms: ["chapel"],
  },
  {
    name: "art",
    heading: "Art Building Rooms",
    img: "/static/art.jpeg",
    rooms: [
      "A101",
      "A102",
      "A104",
      "A106",
      "A107",
      "A200",
      "A201",
      "A204",
      "A206",
      "A207",
      "M001",
      "M010",
      "M011",
      "M103",
      "M104",
      "M105",
      "M107",
    ],
  },
  {
    name: "admin",
    heading: "Admin Building Rooms",
    img: "/static/admin.jpeg",
    rooms: [
      "A100",
      "A110",
      "A124",
      "A135",
      "A136",
      "A237",
      "A300",
      "A301",
      "A302",
      "A303",
      "A304",
      "A308",
      "A309",
      "A310",
      "A320",
      "A321",
      "A330",
      "A331",
    ],
  },
  {
    name: "science",
    heading: "Science Building Rooms",
    img: "/static/science.jpeg",
    rooms: [
      "S101",
      "S102",
      "S103",
      "S104",
      "S105",
      "S203",
      "S204",
      "S207",
      "S210",
      "S300",
      "S301",
      "S304",
      "S308",
      "S309",
      "S400",
    ],
  },
  {
    name: "carter",
    heading: "Carter Building Rooms",
    img: "/static/carter.jpeg",
    rooms: ["Dance Studio", "303", "402", "405", "406"],
  },
  {
    name: "library",
    heading: "Library Building Rooms",
    img: "/static/library.jpeg",
    rooms: ["B28", "B8", "President's Room"],
  },
]

// replace all occurrences only works with regex
export const nameToSlug = (name) => name.trim().toLowerCase().replace(/ /g, "-")
export const slugToName = (name) => name.trim().toLowerCase().replace(/-/g, " ")
